### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Jamesking56** [JeffreyWay/Vagrant-Setup#2]
Hello,

Thanks for the Vagrant setup, its working very well on my Mac!

Only trouble is, what can i put in the `install.sh` file to tell the Vagrant setup to Create the relevant database tables, migrate them and seed them?

Would be great to automate database setup too :)

**Comment by BeingTomGreen** [comment]
You should just be able to do something like:

```
if [ -f /database/base.sql ]
then
    mysql -u root -proot < /database/base.sql
    echo -e "\nInitial MySQL import..."
else
    echo -e "\nNo initial MySQL dump found found... skipping..."
fi
```

I have used something similar to setup a base table, then you can just run `artisan migrate` and `artisan db:seed`.

**Comment by brunowego** [comment]
:+1:

**Comment by Jamesking56** [comment]
Since Homestead now creates tables for you, this isn't relevant anymore.
